# Generated by Django 4.2.5 on 2023-09-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='todoo',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
